
services:
  db:
    image: postgres
    restart: always
    env_file:
      - ./db.env
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./test.sh:/docker-entrypoint-initdb.d/test.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tasks_db"]
      interval: 2s         
      timeout: 5s           
      retries: 5            